export const frequentlyBoughtData = [
  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "smart-watch-black",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "smart-watch-black",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "smart-watch-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "smart-watch-black",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Fluffy Yellow",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    images: [
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
];
export const relatedProducts = [
  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "smart-watch-black",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "smart-watch-black",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "smart-watch-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "smart-watch-black",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Fluffy Yellow",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    images: [
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
];
