// services
export const serviceList = [
  {
    id: "980d2c6a-e463-4ece-ac3a-df27366d6f06",
    icon: "Truck",
    title: "Fast Delivery",
    description: "Start from $10",
  },
  {
    id: "4d545fcc-4354-4197-80eb-04dbc49ea1ec",
    icon: "MoneyGuarantee",
    title: "Money Guarantee",
    description: "7 Days Back",
  },
  {
    id: "8b2af48c-48df-4c25-9eb5-c78ce2ea10f3",
    icon: "AlarmClock",
    title: "365 Days",
    description: "For free return",
  },
  {
    id: "f0edf86f-aa5e-4d32-8988-82aec06b2229",
    icon: "Payment",
    title: "Payment",
    description: "Secure system",
  },
  {
    id: "bda5241f-f3ec-4891-844f-84d911ec572c",
    icon: "OnlineSupport",
    title: "Online Support",
    description: "24/7 daily",
  },
];
export const dealOfTheWeekList = [
  {
    imgUrl: "/assets/images/products/nike-black.png",
    brand: "Extra Large Shoes",
    off: 50,
  },
  {
    imgUrl: "/assets/images/products/nike.png",
    brand: "Nike Shoe Air Max",
    off: 30,
  },
  {
    imgUrl: "/assets/images/products/red-shoe.png",
    brand: "North Face",
    off: 40,
  },
  {
    imgUrl: "/assets/images/products/Fashion/Shoes/7.NikeGreen.png",
    brand: "Nike Green",
    off: 20,
  },
  {
    imgUrl: "/assets/images/products/nike-black.png",
    brand: "Extra Large Shoes",
    off: 50,
  },
  {
    imgUrl: "/assets/images/products/nike.png",
    brand: "Nike Shoe Air Max",
    off: 30,
  },
  {
    imgUrl: "/assets/images/products/red-shoe.png",
    brand: "North Face",
    off: 40,
  },
  {
    imgUrl: "/assets/images/products/Fashion/Shoes/7.NikeGreen.png",
    brand: "Nike Green",
    off: 20,
  },
];
export const hotDealsData = [
  {
    expireDate: "Dec 5, 2024",
    productName: "Apple Watch Series 4 (Black)",
    imgUrl: "/assets/images/products/xiaomi-watch.png",
  },
  {
    expireDate: "Dec 5, 2024",
    productName: "Apple Watch Series 4 (Black)",
    imgUrl: "/assets/images/products/xiaomi-watch.png",
  },
  {
    expireDate: "Dec 5, 2024",
    productName: "Apple Watch Series 4 (Black)",
    imgUrl: "/assets/images/products/xiaomi-watch.png",
  },
];

// products
export const products = [

  //Flash
  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "nike-red",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "north-star-cream",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "puma-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "nike-fluffy-yellow",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Fluffy Yellow",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    images: [
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },

  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "nike-red",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "north-star-cream",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "puma-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "nike-fluffy-yellow",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Fluffy Yellow",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    images: [
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },

  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "nike-red",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "north-star-cream",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "puma-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "nike-fluffy-yellow",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Fluffy Yellow",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    images: [
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "flash-deals",
    },
  },
//New Arrivals

  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "nike-red",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "north-star-cream",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "puma-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "nike-fluffy-yellow",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Fluffy Yellow",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    images: [
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },

  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "nike-red",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "north-star-cream",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "puma-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "nike-fluffy-yellow",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Fluffy Yellow",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    images: [
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "new-arrivals",
    },
  },

  //Trending items//

  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "nike-red",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "north-star-cream",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "puma-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },

  {
    id: "56b18419-a114-4d73-8725-48fa10823479",
    slug: "nike-red",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Red",
    brand: null,
    price: 250,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    images: [
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
      "/assets/images/products/Fashion/Shoes/1.NikeRed.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "9a6ab40e-9af4-442b-a6a1-8abef4b4eaf6",
    slug: "north-star-cream",
    shop: {
      id: "7fac1170-61da-4cac-a163-ce1d41cf6434",
      slug: "word-wide-wishes",
      user: {
        id: "97b2d499-bbaf-4a58-bf94-c74ade65232b",
        email: "Janae64@gmail.com",
        phone: "566.945.9615 x349",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
        password: "8Hg3yVQZwqwnlIo",
        dateOfBirth: "2002-05-01T01:36:12.848Z",
        verified: true,
        name: {
          firstName: "Izabella",
          lastName: "Mraz",
        },
      },
      email: "Melisa24@hotmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "North Star Cream",
    brand: null,
    price: 350,
    size: null,
    colors: [],
    discount: 15,
    thumbnail: "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    images: [
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
      "/assets/images/products/Fashion/Shoes/2.NorthStarCream.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "2317e010-8e7b-460a-8ece-f518a81fc4a1",
    slug: "puma-black",
    shop: {
      id: "3656fa23-850b-4660-9c97-475a4afc1001",
      slug: "scarlett-beauty",
      user: {
        id: "ca714b9e-06f6-42a7-8185-2820c2828756",
        email: "Connie.Hegmann@gmail.com",
        phone: "(530) 913-2158",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/643.jpg",
        password: "qj3I80rxzgZ9bLj",
        dateOfBirth: "1992-06-09T21:28:49.616Z",
        verified: true,
        name: {
          firstName: "Sadye",
          lastName: "Wilkinson",
        },
      },
      email: "Vito.Parker@hotmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Puma Black",
    brand: null,
    price: 150,
    size: null,
    colors: [],
    discount: 28,
    thumbnail: "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    images: [
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
      "/assets/images/products/Fashion/Shoes/3.PumaBlack.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
  {
    id: "117e49e6-bc83-49aa-8b8b-c0632d897ad7",
    slug: "nike-fluffy-yellow",
    shop: {
      id: "a499def2-78dd-4afd-a367-7b6007f0f6e5",
      slug: "constant-shoppers",
      user: {
        id: "c86e97b9-690f-42ce-9444-6de7b7936072",
        email: "Brannon88@gmail.com",
        phone: "358-987-4881 x2566",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
        password: "boKxxIP_if6PmzS",
        dateOfBirth: "1985-03-28T13:30:12.771Z",
        verified: true,
        name: {
          firstName: "Rodrick",
          lastName: "Farrell",
        },
      },
      email: "Gretchen54@gmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Nike Fluffy Yellow",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 21,
    thumbnail: "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    images: [
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
      "/assets/images/products/Fashion/Shoes/4.NikeFluffyYellow.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "fashion-1",
      type: "trending-items",
    },
  },
];
